---
# tasks file for epel.local

- name: install epel package on CentOS
  yum:
     name:
        - epel-release
     state: present
     update_cache: yes
  when:
    - ansible_distribution == 'CentOS'


