- name: install support packages on Ubuntu
  apt:
     name:
        - python-apt
        - python-mysqldb
        - python3-mysqldb
        - mysql-client
        - mc
     state: present
     update_cache: yes
     cache_valid_time: 3600
  when:
    - ansible_distribution == 'Ubuntu'




