

- name: install mysql package
  apt:
    name: mysql-server
    state: present


- name: start mysql service
  service:
     name: mysql
     state: started


- name: change mysql password for  
          root@'::1' 
          root@'{ inventory_hostname }'
          root@'127.0.0.1'
          root@'localhost'
  mysql_user:
     name: root
     password: "{{ mysql_root_pass }}"
     host: "{{ item }}"
     login_unix_socket: /run/mysqld/mysqld.sock
#     login_password: "1 "
#     login_user: root
#     login_host: localhost
  with_items:
     - '::1'
     - "{{ inventory_hostname }}"
     - '127.0.0.1'
     - localhost
  no_log: true
  ignore_errors: false


- name: copy .my.cnf 
  template:
       src: my.cnf.yml
       dest: /root/.my.cnf
       owner: root
       mode: 0600









