Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.ssh.forward_agent = true


# Variables
INSTANCE_NAME_PREFIX = "gitlab"
NUM_INSTANCES = 1
host_vars = {}


# пути к плейбукам
  require 'fileutils'
  PLAYBOOK_PHASE_PATH   = File.join(File.dirname(__FILE__), "gitlab-ansible-playbook.yml")









(1..NUM_INSTANCES).each do |i|
  config.vm.define "#{INSTANCE_NAME_PREFIX}-#{i}" do |node|
    node.vm.box_download_insecure = true
    node.vm.box = "ubuntu/xenial64"
    node.vm.network "private_network", ip: "192.168.11.#{i+2}"
    node.vm.hostname = "#{INSTANCE_NAME_PREFIX}-#{i}"
       node.vm.provider "virtualbox" do |v|
         v.name = "#{INSTANCE_NAME_PREFIX}-#{i}"
         v.memory = 7000
         v.cpus = 5
         v.customize ["modifyvm", :id, "--vram", "8"] # ubuntu defaults to 256 MB which is a waste of precious RAM
         v.customize ["modifyvm", :id, "--audio", "none"]
       end


   vm_name="#{INSTANCE_NAME_PREFIX}-#{i}"

   host_vars[vm_name] = {
       "ip" => "192.168.11.#{i+2}",
       "access_ip" => "192.168.11.#{i+2}"
   }



    # Only execute the Ansible provisioner once, when all the machines are up and ready.
    if i == NUM_INSTANCES
       node.vm.provision "ping", type: "ansible" do |ansible|
          ansible.playbook = "#{PLAYBOOK_PHASE_PATH}"
          ansible.become = true
          ansible.limit = "all,localhost"
          ansible.host_key_checking = false
          ansible.host_vars = host_vars
          ansible.raw_arguments = ["--forks=#{NUM_INSTANCES}", "--flush-cache", "-e ansible_ssh_user=vagrant"]
        end
     end




  end



end




end
