# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"




Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
#  config.vm.box = "opscode-ubuntu-12.04"
     # use the same key for every machine
     config.ssh.insert_key = false


  config.vm.box = "ubuntu/xenial64"




  config.vm.define "mastery" do |mastery|
    mastery.vm.network :private_network, ip: "192.168.61.11"
    mastery.vm.network "forwarded_port", guest: 8080, host: 8082
          mastery.vm.provider "virtualbox" do |hw|
            hw.memory = "480"
            hw.cpus = 1
          end
  end






  config.vm.define "backend" do |backend|
    backend.vm.network :private_network, ip: "192.168.61.12"
          backend.vm.provider "virtualbox" do |hw|
            hw.memory = "550"
            hw.cpus = 1
          end

  end


  config.vm.define "db2" do |backend|
    backend.vm.network :private_network, ip: "192.168.61.13"
          backend.vm.provider "virtualbox" do |hw|
            hw.memory = "550"
            hw.cpus = 1
          end

  end





end


